2021-06-07 00:22:27,413 INFO frappe Checking incoming IMAP email server imap.gmail.com:993 ssl=1...
Site: acs.v1
Form Dict: {'doc': '{"docstatus":0,"doctype":"Email Domain","name":"new-email-domain-1","__islocal":1,"__unsaved":1,"owner":"Administrator","use_imap":1,"use_ssl":1,"attachment_limit":1,"use_tls":1,"use_ssl_for_outgoing":1,"append_emails_to_sent_folder":0,"email_id":"abc@gmail.com","domain_name":"gmail.com","email_server":"imap.gmail.com","incoming_port":"993","smtp_server":"smtp.gmail.com","smtp_port":"587"}', 'action': 'Save', 'cmd': 'frappe.desk.form.save.savedocs'}
2021-06-07 00:22:28,372 INFO frappe Checking outgoing SMTPS email server smtp.gmail.com:587...
Site: acs.v1
Form Dict: {'doc': '{"docstatus":0,"doctype":"Email Domain","name":"new-email-domain-1","__islocal":1,"__unsaved":1,"owner":"Administrator","use_imap":1,"use_ssl":1,"attachment_limit":1,"use_tls":1,"use_ssl_for_outgoing":1,"append_emails_to_sent_folder":0,"email_id":"abc@gmail.com","domain_name":"gmail.com","email_server":"imap.gmail.com","incoming_port":"993","smtp_server":"smtp.gmail.com","smtp_port":"587"}', 'action': 'Save', 'cmd': 'frappe.desk.form.save.savedocs'}
2021-06-07 00:22:29,114 WARNING frappe Outgoing email account "smtp.gmail.com" not correct
Site: acs.v1
Form Dict: {'doc': '{"docstatus":0,"doctype":"Email Domain","name":"new-email-domain-1","__islocal":1,"__unsaved":1,"owner":"Administrator","use_imap":1,"use_ssl":1,"attachment_limit":1,"use_tls":1,"use_ssl_for_outgoing":1,"append_emails_to_sent_folder":0,"email_id":"abc@gmail.com","domain_name":"gmail.com","email_server":"imap.gmail.com","incoming_port":"993","smtp_server":"smtp.gmail.com","smtp_port":"587"}', 'action': 'Save', 'cmd': 'frappe.desk.form.save.savedocs'}
Traceback (most recent call last):
  File "/home/my_user/frappe-bench/apps/frappe/frappe/email/doctype/email_domain/email_domain.py", line 68, in validate
    cint(self.smtp_port) or None)
  File "/usr/lib/python3.6/smtplib.py", line 1031, in __init__
    source_address)
  File "/usr/lib/python3.6/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python3.6/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python3.6/smtplib.py", line 1039, in _get_socket
    server_hostname=self._host)
  File "/usr/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib/python3.6/ssl.py", line 814, in __init__
    self.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:833)
2021-06-07 00:22:37,315 INFO frappe Checking incoming IMAP email server imap.gmail.com:993 ssl=1...
Site: acs.v1
Form Dict: {'doc': '{"docstatus":0,"doctype":"Email Domain","name":"new-email-domain-1","__islocal":1,"__unsaved":1,"owner":"Administrator","use_imap":1,"use_ssl":1,"attachment_limit":1,"use_tls":1,"use_ssl_for_outgoing":1,"append_emails_to_sent_folder":0,"email_id":"abc@gmail.com","domain_name":"gmail.com","email_server":"imap.gmail.com","incoming_port":"993","smtp_server":"smtp.gmail.com","smtp_port":"465"}', 'action': 'Save', 'cmd': 'frappe.desk.form.save.savedocs'}
2021-06-07 00:22:38,277 INFO frappe Checking outgoing SMTPS email server smtp.gmail.com:465...
Site: acs.v1
Form Dict: {'doc': '{"docstatus":0,"doctype":"Email Domain","name":"new-email-domain-1","__islocal":1,"__unsaved":1,"owner":"Administrator","use_imap":1,"use_ssl":1,"attachment_limit":1,"use_tls":1,"use_ssl_for_outgoing":1,"append_emails_to_sent_folder":0,"email_id":"abc@gmail.com","domain_name":"gmail.com","email_server":"imap.gmail.com","incoming_port":"993","smtp_server":"smtp.gmail.com","smtp_port":"465"}', 'action': 'Save', 'cmd': 'frappe.desk.form.save.savedocs'}
2021-06-07 00:25:21,637 INFO frappe Checking incoming IMAP email server imap.gmail.com:993 ssl=1...
Site: acs.v1
Form Dict: {'doc': '{"name":"gmail.com","owner":"Administrator","creation":"2021-06-07 09:22:37.305199","modified":"2021-06-07 09:22:37.305199","modified_by":"Administrator","idx":0,"docstatus":0,"domain_name":"gmail.com","email_id":"abc@gmail.com","email_server":"imap.gmail.com","use_imap":1,"use_ssl":1,"incoming_port":"993","attachment_limit":1,"smtp_server":"smtp.gmail.com","use_tls":0,"use_ssl_for_outgoing":1,"append_emails_to_sent_folder":0,"smtp_port":"465","doctype":"Email Domain","__last_sync_on":"2021-06-06T23:25:17.379Z","__unsaved":1}', 'action': 'Save', 'cmd': 'frappe.desk.form.save.savedocs'}
2021-06-07 00:25:22,610 INFO frappe Checking outgoing SMTPS email server smtp.gmail.com:465...
Site: acs.v1
Form Dict: {'doc': '{"name":"gmail.com","owner":"Administrator","creation":"2021-06-07 09:22:37.305199","modified":"2021-06-07 09:22:37.305199","modified_by":"Administrator","idx":0,"docstatus":0,"domain_name":"gmail.com","email_id":"abc@gmail.com","email_server":"imap.gmail.com","use_imap":1,"use_ssl":1,"incoming_port":"993","attachment_limit":1,"smtp_server":"smtp.gmail.com","use_tls":0,"use_ssl_for_outgoing":1,"append_emails_to_sent_folder":0,"smtp_port":"465","doctype":"Email Domain","__last_sync_on":"2021-06-06T23:25:17.379Z","__unsaved":1}', 'action': 'Save', 'cmd': 'frappe.desk.form.save.savedocs'}
2021-06-07 02:38:49,902 ERROR frappe New Exception collected with id: 2021-06-07 02:38:49.250447-119.152.130.102-fb3
Site: acs.v1
Form Dict: {'doc': '{"docstatus":0,"doctype":"Staff Screening","name":"new-staff-screening-1","__islocal":1,"__unsaved":1,"owner":"Administrator","version":"0","dt8":0,"dt9":0,"dt10":0,"dt12":"Yes","dt13":"Available","dt14":"Available","dt15":"Available","dt16":"Valid Australian License","dtt16":"Available","checkpl":"Yes","vevocheckuploaded":"0","score4":null,"user":"ahmed.syed@vccg.com.au","vevocheckexpiry":"2021-06-01"}', 'action': 'Save', 'cmd': 'frappe.desk.form.save.savedocs'}
2021-06-08 03:46:19,729 ERROR frappe New Exception collected with id: 2021-06-08 03:46:18.892125-103.11.207.116-90c
Site: acs.v1
Form Dict: {'sid': 'Guest', 'cmd': 'frappe.realtime.get_user_info'}
2021-06-08 03:46:19,733 ERROR frappe New Exception collected with id: 2021-06-08 03:46:18.892169-103.11.207.116-b6b
Site: acs.v1
Form Dict: {'sid': 'Guest', 'cmd': 'frappe.realtime.get_user_info'}
2021-06-08 03:46:19,810 ERROR frappe New Exception collected with id: 2021-06-08 03:46:18.892318-103.11.207.116-2b0
Site: acs.v1
Form Dict: {'sid': 'Guest', 'cmd': 'frappe.realtime.get_user_info'}
2021-06-08 03:46:20,158 ERROR frappe New Exception collected with id: 2021-06-08 03:46:20.154975-103.11.207.116-915
Site: acs.v1
Form Dict: {'sid': 'Guest', 'cmd': 'frappe.realtime.get_user_info'}
2021-06-08 03:46:22,397 ERROR frappe New Exception collected with id: 2021-06-08 03:46:22.252624-103.11.207.116-9b6
Site: acs.v1
Form Dict: {'sid': 'Guest', 'cmd': 'frappe.realtime.get_user_info'}
2021-06-08 03:46:22,404 ERROR frappe New Exception collected with id: 2021-06-08 03:46:22.258905-103.11.207.116-1b2
Site: acs.v1
Form Dict: {'sid': 'Guest', 'cmd': 'frappe.realtime.get_user_info'}
2021-06-08 03:57:00,610 ERROR frappe New Exception collected with id: 2021-06-08 03:57:00.607190-119.152.130.102-6c0
Site: acs.v1
Form Dict: {'cmd': 'login', 'usr': 'Administrator', 'pwd': '@Aeroplane1.v', 'device': 'desktop'}
2021-06-08 04:01:19,409 ERROR frappe New Exception collected with id: 2021-06-08 04:01:19.405245-119.152.130.102-981
Site: acs.v1
Form Dict: {'cmd': 'login', 'usr': 'Administrator', 'pwd': '@Aeroplane1.v', 'device': 'desktop'}
2021-06-08 04:02:19,771 ERROR frappe New Exception collected with id: 2021-06-08 04:02:19.760398-119.152.130.102-918
Site: acs.v1
Form Dict: {'cmd': 'login', 'usr': 'Administrator', 'pwd': '@Aeroplane1.v', 'device': 'desktop'}
2021-06-08 04:18:51,815 ERROR frappe New Exception collected with id: 2021-06-08 04:18:51.809652-103.11.207.116-6ad
Site: acs.v1
Form Dict: {'sid': 'Guest', 'cmd': 'frappe.realtime.get_user_info'}
2021-06-08 04:21:13,113 ERROR frappe New Exception collected with id: 2021-06-08 04:21:13.108603-103.11.207.116-f66
Site: acs.v1
Form Dict: {'sid': '2782ccd1a21ef62a9650543b4536c815abf088db6324453b582fa3d3', 'cmd': 'frappe.realtime.get_user_info'}
2021-06-08 04:27:13,099 ERROR frappe New Exception collected with id: 2021-06-08 04:27:13.076200-103.11.207.116-8d3
Site: acs.v1
Form Dict: {'sid': '2782ccd1a21ef62a9650543b4536c815abf088db6324453b582fa3d3', 'cmd': 'frappe.realtime.get_user_info'}
2021-06-08 04:27:50,993 ERROR frappe New Exception collected with id: 2021-06-08 04:27:50.987876-103.11.207.116-447
Site: acs.v1
Form Dict: {'sid': 'Guest', 'cmd': 'frappe.realtime.get_user_info'}
2021-06-08 04:28:15,435 ERROR frappe New Exception collected with id: 2021-06-08 04:28:15.430109-103.11.207.116-f89
Site: acs.v1
Form Dict: {'sid': 'Guest', 'cmd': 'frappe.realtime.get_user_info'}
2021-06-08 04:28:15,483 ERROR frappe New Exception collected with id: 2021-06-08 04:28:15.470773-103.11.207.116-504
Site: acs.v1
Form Dict: {'sid': 'Guest', 'cmd': 'frappe.realtime.get_user_info'}
2021-06-08 04:56:23,112 ERROR frappe New Exception collected with id: 2021-06-08 04:56:23.105256-103.11.207.116-dcf
Site: acs.v1
Form Dict: {'sid': '2782ccd1a21ef62a9650543b4536c815abf088db6324453b582fa3d3', 'cmd': 'frappe.realtime.get_user_info'}
2021-06-08 05:09:42,137 ERROR frappe New Exception collected with id: 2021-06-08 05:09:42.132654-103.11.207.116-f8d
Site: acs.v1
Form Dict: {'sid': '2782ccd1a21ef62a9650543b4536c815abf088db6324453b582fa3d3', 'cmd': 'frappe.realtime.get_user_info'}
2021-06-08 05:10:43,215 ERROR frappe New Exception collected with id: 2021-06-08 05:10:43.210207-103.11.207.116-ab2
Site: acs.v1
Form Dict: {'sid': '2782ccd1a21ef62a9650543b4536c815abf088db6324453b582fa3d3', 'cmd': 'frappe.realtime.get_user_info'}
2021-06-08 05:31:22,394 ERROR frappe New Exception collected with id: 2021-06-08 05:31:22.388771-103.11.207.116-659
Site: acs.v1
Form Dict: {'sid': '2782ccd1a21ef62a9650543b4536c815abf088db6324453b582fa3d3', 'cmd': 'frappe.realtime.get_user_info'}
2021-06-08 05:36:43,614 ERROR frappe New Exception collected with id: 2021-06-08 05:36:43.606667-103.11.207.116-74f
Site: acs.v1
Form Dict: {'sid': '2782ccd1a21ef62a9650543b4536c815abf088db6324453b582fa3d3', 'cmd': 'frappe.realtime.get_user_info'}
2021-06-08 05:39:42,330 ERROR frappe New Exception collected with id: 2021-06-08 05:39:42.324014-103.11.207.116-138
Site: acs.v1
Form Dict: {'sid': '2782ccd1a21ef62a9650543b4536c815abf088db6324453b582fa3d3', 'cmd': 'frappe.realtime.get_user_info'}
2021-06-08 05:40:08,636 ERROR frappe New Exception collected with id: 2021-06-08 05:40:08.631842-103.11.207.116-f5e
Site: acs.v1
Form Dict: {'sid': 'Guest', 'cmd': 'frappe.realtime.get_user_info'}
2021-06-08 05:49:14,017 ERROR frappe New Exception collected with id: 2021-06-08 05:49:14.012309-103.11.207.116-a3e
Site: acs.v1
Form Dict: {'sid': 'Guest', 'cmd': 'frappe.realtime.get_user_info'}
2021-06-08 05:49:14,024 ERROR frappe New Exception collected with id: 2021-06-08 05:49:14.018989-103.11.207.116-ba8
Site: acs.v1
Form Dict: {'sid': 'Guest', 'cmd': 'frappe.realtime.get_user_info'}
2021-06-08 05:49:23,755 ERROR frappe New Exception collected with id: 2021-06-08 05:49:23.751004-103.11.207.116-f3d
Site: acs.v1
Form Dict: {'sid': '2782ccd1a21ef62a9650543b4536c815abf088db6324453b582fa3d3', 'cmd': 'frappe.realtime.get_user_info'}
2021-06-08 05:58:37,631 ERROR frappe New Exception collected with id: 2021-06-08 05:58:37.624906-103.11.207.116-cd3
Site: acs.v1
Form Dict: {'sid': '2782ccd1a21ef62a9650543b4536c815abf088db6324453b582fa3d3', 'cmd': 'frappe.realtime.get_user_info'}
2021-06-08 06:01:24,471 ERROR frappe New Exception collected with id: 2021-06-08 06:01:24.464455-103.11.207.116-14f
Site: acs.v1
Form Dict: {'sid': '2782ccd1a21ef62a9650543b4536c815abf088db6324453b582fa3d3', 'cmd': 'frappe.realtime.get_user_info'}
2021-06-08 06:09:38,316 ERROR frappe New Exception collected with id: 2021-06-08 06:09:38.309407-103.11.207.116-6b7
Site: acs.v1
Form Dict: {'sid': 'Guest', 'cmd': 'frappe.realtime.get_user_info'}
2021-06-08 06:09:38,317 ERROR frappe New Exception collected with id: 2021-06-08 06:09:38.310048-103.11.207.116-27c
Site: acs.v1
Form Dict: {'sid': 'Guest', 'cmd': 'frappe.realtime.get_user_info'}
2021-06-08 06:09:38,505 ERROR frappe New Exception collected with id: 2021-06-08 06:09:38.499271-103.11.207.116-b5f
Site: acs.v1
Form Dict: {'sid': 'Guest', 'cmd': 'frappe.realtime.get_user_info'}
2021-06-08 06:19:00,257 ERROR frappe New Exception collected with id: 2021-06-08 06:19:00.250663-103.11.207.116-8bd
Site: acs.v1
Form Dict: {'sid': 'Guest', 'cmd': 'frappe.realtime.get_user_info'}
2021-06-08 06:19:00,262 ERROR frappe New Exception collected with id: 2021-06-08 06:19:00.254388-103.11.207.116-3f8
Site: acs.v1
Form Dict: {'sid': 'Guest', 'cmd': 'frappe.realtime.get_user_info'}
2021-06-08 06:28:36,249 ERROR frappe New Exception collected with id: 2021-06-08 06:28:36.243977-103.11.207.116-3c2
Site: acs.v1
Form Dict: {'sid': 'Guest', 'cmd': 'frappe.realtime.get_user_info'}
2021-06-08 06:29:06,270 ERROR frappe New Exception collected with id: 2021-06-08 06:29:06.265516-103.11.207.116-fa0
Site: acs.v1
Form Dict: {'sid': 'Guest', 'cmd': 'frappe.realtime.get_user_info'}
2021-06-08 06:45:08,654 ERROR frappe New Exception collected with id: 2021-06-08 06:45:08.649251-103.11.207.116-2d2
Site: acs.v1
Form Dict: {'sid': 'Guest', 'cmd': 'frappe.realtime.get_user_info'}
2021-06-08 06:53:16,517 ERROR frappe New Exception collected with id: 2021-06-08 06:53:16.512043-103.11.207.116-3d2
Site: acs.v1
Form Dict: {'sid': '20a7b04c73d6e9d96b072ece9e694b150e34f7fb888d1695d1ca3b20', 'cmd': 'frappe.realtime.get_user_info'}
2021-06-08 06:54:35,368 ERROR frappe New Exception collected with id: 2021-06-08 06:54:35.362676-103.11.207.116-7d0
Site: acs.v1
Form Dict: {'sid': 'Guest', 'cmd': 'frappe.realtime.get_user_info'}
2021-06-08 06:54:35,371 ERROR frappe New Exception collected with id: 2021-06-08 06:54:35.365526-103.11.207.116-df9
Site: acs.v1
Form Dict: {'sid': 'Guest', 'cmd': 'frappe.realtime.get_user_info'}
2021-06-08 06:55:51,927 ERROR frappe New Exception collected with id: 2021-06-08 06:55:51.925372-119.152.130.102-ebb
Site: acs.v1
Form Dict: {'cmd': 'login', 'usr': 'Administrator', 'pwd': '@Aeroplane1.v', 'device': 'desktop'}
2021-06-08 06:57:08,252 ERROR frappe New Exception collected with id: 2021-06-08 06:57:08.249494-119.152.130.102-052
Site: acs.v1
Form Dict: {'cmd': 'login', 'usr': 'Administrator', 'pwd': '@Aeroplane1.v', 'device': 'desktop'}
2021-06-08 06:59:11,995 ERROR frappe New Exception collected with id: 2021-06-08 06:59:11.988252-103.11.207.116-9bd
Site: acs.v1
Form Dict: {'sid': '62fde14b3d5f46cbc2e4c14bca7178509419f4f09ca3cd104b6d9739', 'cmd': 'frappe.realtime.get_user_info'}
2021-06-08 07:04:49,117 ERROR frappe New Exception collected with id: 2021-06-08 07:04:49.111391-103.11.207.116-be5
Site: acs.v1
Form Dict: {'sid': '62fde14b3d5f46cbc2e4c14bca7178509419f4f09ca3cd104b6d9739', 'cmd': 'frappe.realtime.get_user_info'}
2021-06-08 07:05:15,922 ERROR frappe New Exception collected with id: 2021-06-08 07:05:15.916824-103.11.207.116-6d7
Site: acs.v1
Form Dict: {'sid': 'Guest', 'cmd': 'frappe.realtime.get_user_info'}
2021-06-08 07:15:41,424 ERROR frappe New Exception collected with id: 2021-06-08 07:15:41.417320-103.11.207.116-e84
Site: acs.v1
Form Dict: {'sid': '62fde14b3d5f46cbc2e4c14bca7178509419f4f09ca3cd104b6d9739', 'cmd': 'frappe.realtime.get_user_info'}
2021-06-08 07:15:48,568 ERROR frappe New Exception collected with id: 2021-06-08 07:15:48.562633-103.11.207.116-d18
Site: acs.v1
Form Dict: {'sid': '62fde14b3d5f46cbc2e4c14bca7178509419f4f09ca3cd104b6d9739', 'cmd': 'frappe.realtime.get_user_info'}
2021-06-08 07:21:07,527 ERROR frappe New Exception collected with id: 2021-06-08 07:21:07.524088-119.152.130.102-444
Site: acs.v1
Form Dict: {'cmd': 'login', 'usr': 'Administrator', 'pwd': '@Aeroplane1.v', 'device': 'desktop'}
2021-06-08 07:24:19,930 ERROR frappe New Exception collected with id: 2021-06-08 07:24:19.927120-119.152.130.102-b5d
Site: acs.v1
Form Dict: {'cmd': 'login', 'usr': 'Administrator', 'pwd': '@Aeroplane1.v', 'device': 'desktop'}
2021-06-08 07:24:22,516 ERROR frappe New Exception collected with id: 2021-06-08 07:24:22.512426-119.152.130.102-c8d
Site: acs.v1
Form Dict: {'cmd': 'login', 'usr': 'Administrator', 'pwd': '@Aeroplane1.v', 'device': 'desktop'}
2021-06-08 07:25:29,758 ERROR frappe New Exception collected with id: 2021-06-08 07:25:29.752079-103.11.207.116-c74
Site: acs.v1
Form Dict: {'sid': 'Guest', 'cmd': 'frappe.realtime.get_user_info'}
2021-06-08 07:28:26,079 ERROR frappe New Exception collected with id: 2021-06-08 07:28:26.075934-119.152.130.102-05e
Site: acs.v1
Form Dict: {'cmd': 'login', 'usr': 'Administrator', 'pwd': '@Aeroplane1.v', 'device': 'desktop'}
2021-06-08 07:33:32,308 ERROR frappe Could not take error snapshot: 'Document' object has no attribute 'docstatus'
Site: acs.v1
Form Dict: {'doctype': 'DocType', 'fields': '["`tabDocType`.`name`","`tabDocType`.`owner`","`tabDocType`.`creation`","`tabDocType`.`modified`","`tabDocType`.`modified_by`","`tabDocType`.`_user_tags`","`tabDocType`.`_comments`","`tabDocType`.`_assign`","`tabDocType`.`_liked_by`","`tabDocType`.`docstatus`","`tabDocType`.`parent`","`tabDocType`.`parenttype`","`tabDocType`.`parentfield`","`tabDocType`.`idx`","`tabDocType`.`module`","`tabDocType`.`color`"]', 'filters': '[["DocType","name","like","%Policies%"],["DocType","name","=","User"]]', 'order_by': '`tabDocType`.`modified` desc', 'start': '0', 'page_length': '20', 'view': 'List', 'with_comment_count': 'true'}
Traceback (most recent call last):
  File "/home/my_user/frappe-bench/apps/frappe/frappe/app.py", line 54, in application
    init_request(request)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/app.py", line 128, in init_request
    frappe.local.http_request = frappe.auth.HTTPRequest()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/auth.py", line 52, in __init__
    frappe.local.login_manager = LoginManager()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/auth.py", line 114, in __init__
    self.make_session(resume=True)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/auth.py", line 196, in make_session
    full_name=self.full_name, user_type=self.user_type)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/sessions.py", line 189, in __init__
    self.resume()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/sessions.py", line 256, in resume
    validate_ip_address(self.user)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/auth.py", line 380, in validate_ip_address
    user = frappe.get_cached_doc("User", user) if not frappe.flags.in_test else frappe.get_doc("User", user)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/__init__.py", line 807, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/__init__.py", line 850, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/document.py", line 74, in get_doc
    return controller(*args, **kwargs)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/document.py", line 112, in __init__
    self.load_from_db()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/document.py", line 141, in load_from_db
    if not getattr(self, "_metaclass", False) and self.meta.issingle:
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/base_document.py", line 91, in meta
    self._meta = frappe.get_meta(self.doctype)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/__init__.py", line 881, in get_meta
    return frappe.model.meta.get_meta(doctype, cached=cached)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/meta.py", line 37, in get_meta
    meta = Meta(doctype)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/meta.py", line 84, in __init__
    self.process()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/meta.py", line 102, in process
    self.apply_property_setters()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/meta.py", line 319, in apply_property_setters
    doc_type=%s""", (self.name,), as_dict=1)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/database/database.py", line 146, in sql
    self._cursor.execute(query, values)
  File "/home/my_user/frappe-bench/env/lib/python3.6/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/home/my_user/frappe-bench/env/lib/python3.6/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/my_user/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/my_user/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/my_user/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 1163, in read
    self._read_result_packet(first_packet)
  File "/home/my_user/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 1236, in _read_result_packet
    self._read_rowdata_packet()
  File "/home/my_user/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 1270, in _read_rowdata_packet
    packet = self.connection._read_packet()
  File "/home/my_user/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/my_user/frappe-bench/env/lib/python3.6/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/my_user/frappe-bench/env/lib/python3.6/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1412, 'Table definition has changed, please retry transaction')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/my_user/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python3.6/inspect.py", line 1262, in formatargvalues
    specs.append(convert(args[i]))
  File "/usr/lib/python3.6/inspect.py", line 1259, in convert
    return formatarg(name) + formatvalue(locals[name])
  File "/home/my_user/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in <lambda>
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python3.6/reprlib.py", line 55, in repr
    return self.repr1(x, self.maxlevel)
  File "/usr/lib/python3.6/pydoc.py", line 1042, in repr1
    return cram(stripid(repr(x)), self.maxother)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/document.py", line 1354, in __repr__
    docstatus = f" docstatus={self.docstatus}" if self.docstatus else ""
AttributeError: 'Document' object has no attribute 'docstatus'
2021-06-08 07:33:32,340 ERROR frappe Could not take error snapshot: 'Document' object has no attribute 'docstatus'
Site: acs.v1
Form Dict: {'doctype': 'DocType', 'fields': '["`tabDocType`.`name`","`tabDocType`.`owner`","`tabDocType`.`creation`","`tabDocType`.`modified`","`tabDocType`.`modified_by`","`tabDocType`.`_user_tags`","`tabDocType`.`_comments`","`tabDocType`.`_assign`","`tabDocType`.`_liked_by`","`tabDocType`.`docstatus`","`tabDocType`.`parent`","`tabDocType`.`parenttype`","`tabDocType`.`parentfield`","`tabDocType`.`idx`","`tabDocType`.`module`","`tabDocType`.`color`"]', 'filters': '[["DocType","module","=","Participants"],["DocType","name","=","User"]]', 'order_by': '`tabDocType`.`modified` desc', 'start': '0', 'page_length': '20', 'view': 'List', 'with_comment_count': 'true'}
Traceback (most recent call last):
  File "/home/my_user/frappe-bench/apps/frappe/frappe/app.py", line 54, in application
    init_request(request)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/app.py", line 128, in init_request
    frappe.local.http_request = frappe.auth.HTTPRequest()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/auth.py", line 52, in __init__
    frappe.local.login_manager = LoginManager()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/auth.py", line 114, in __init__
    self.make_session(resume=True)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/auth.py", line 196, in make_session
    full_name=self.full_name, user_type=self.user_type)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/sessions.py", line 189, in __init__
    self.resume()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/sessions.py", line 256, in resume
    validate_ip_address(self.user)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/auth.py", line 380, in validate_ip_address
    user = frappe.get_cached_doc("User", user) if not frappe.flags.in_test else frappe.get_doc("User", user)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/__init__.py", line 807, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/__init__.py", line 850, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/document.py", line 74, in get_doc
    return controller(*args, **kwargs)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/document.py", line 112, in __init__
    self.load_from_db()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/document.py", line 141, in load_from_db
    if not getattr(self, "_metaclass", False) and self.meta.issingle:
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/base_document.py", line 91, in meta
    self._meta = frappe.get_meta(self.doctype)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/__init__.py", line 881, in get_meta
    return frappe.model.meta.get_meta(doctype, cached=cached)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/meta.py", line 37, in get_meta
    meta = Meta(doctype)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/meta.py", line 84, in __init__
    self.process()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/meta.py", line 105, in process
    self.set_custom_permissions()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/meta.py", line 417, in set_custom_permissions
    filters=dict(parent=self.name), update=dict(doctype='Custom DocPerm'))
  File "/home/my_user/frappe-bench/apps/frappe/frappe/__init__.py", line 1435, in get_all
    return get_list(doctype, *args, **kwargs)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/__init__.py", line 1408, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(*args, **kwargs)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/db_query.py", line 101, in execute
    self.columns = self.get_table_columns()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/db_query.py", line 338, in get_table_columns
    return get_table_columns(self.doctype)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/meta.py", line 49, in get_table_columns
    return frappe.db.get_table_columns(doctype)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/database/database.py", line 896, in get_table_columns
    raise self.TableMissingError('DocType', doctype)
pymysql.err.ProgrammingError: ('DocType', 'Custom DocPerm')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/my_user/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python3.6/inspect.py", line 1262, in formatargvalues
    specs.append(convert(args[i]))
  File "/usr/lib/python3.6/inspect.py", line 1259, in convert
    return formatarg(name) + formatvalue(locals[name])
  File "/home/my_user/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in <lambda>
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python3.6/reprlib.py", line 55, in repr
    return self.repr1(x, self.maxlevel)
  File "/usr/lib/python3.6/pydoc.py", line 1042, in repr1
    return cram(stripid(repr(x)), self.maxother)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/document.py", line 1354, in __repr__
    docstatus = f" docstatus={self.docstatus}" if self.docstatus else ""
AttributeError: 'Document' object has no attribute 'docstatus'
2021-06-08 07:33:32,400 ERROR frappe Could not take error snapshot: 'Document' object has no attribute 'docstatus'
Site: acs.v1
Form Dict: {'doctype': 'DocType', 'fields': '["`tabDocType`.`name`","`tabDocType`.`owner`","`tabDocType`.`creation`","`tabDocType`.`modified`","`tabDocType`.`modified_by`","`tabDocType`.`_user_tags`","`tabDocType`.`_comments`","`tabDocType`.`_assign`","`tabDocType`.`_liked_by`","`tabDocType`.`docstatus`","`tabDocType`.`parent`","`tabDocType`.`parenttype`","`tabDocType`.`parentfield`","`tabDocType`.`idx`","`tabDocType`.`module`","`tabDocType`.`color`"]', 'filters': '[["DocType","name","like","%Policies%"],["DocType","name","=","Custom Field"]]', 'order_by': '`tabDocType`.`modified` desc', 'start': '0', 'page_length': '20', 'view': 'List', 'with_comment_count': 'true'}
Traceback (most recent call last):
  File "/home/my_user/frappe-bench/apps/frappe/frappe/app.py", line 54, in application
    init_request(request)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/app.py", line 128, in init_request
    frappe.local.http_request = frappe.auth.HTTPRequest()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/auth.py", line 52, in __init__
    frappe.local.login_manager = LoginManager()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/auth.py", line 114, in __init__
    self.make_session(resume=True)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/auth.py", line 196, in make_session
    full_name=self.full_name, user_type=self.user_type)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/sessions.py", line 189, in __init__
    self.resume()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/sessions.py", line 256, in resume
    validate_ip_address(self.user)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/auth.py", line 380, in validate_ip_address
    user = frappe.get_cached_doc("User", user) if not frappe.flags.in_test else frappe.get_doc("User", user)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/__init__.py", line 807, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/__init__.py", line 850, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/document.py", line 74, in get_doc
    return controller(*args, **kwargs)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/document.py", line 112, in __init__
    self.load_from_db()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/document.py", line 141, in load_from_db
    if not getattr(self, "_metaclass", False) and self.meta.issingle:
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/base_document.py", line 91, in meta
    self._meta = frappe.get_meta(self.doctype)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/__init__.py", line 881, in get_meta
    return frappe.model.meta.get_meta(doctype, cached=cached)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/meta.py", line 37, in get_meta
    meta = Meta(doctype)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/meta.py", line 84, in __init__
    self.process()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/meta.py", line 105, in process
    self.set_custom_permissions()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/meta.py", line 417, in set_custom_permissions
    filters=dict(parent=self.name), update=dict(doctype='Custom DocPerm'))
  File "/home/my_user/frappe-bench/apps/frappe/frappe/__init__.py", line 1435, in get_all
    return get_list(doctype, *args, **kwargs)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/__init__.py", line 1408, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(*args, **kwargs)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/db_query.py", line 101, in execute
    self.columns = self.get_table_columns()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/db_query.py", line 338, in get_table_columns
    return get_table_columns(self.doctype)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/meta.py", line 49, in get_table_columns
    return frappe.db.get_table_columns(doctype)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/database/database.py", line 896, in get_table_columns
    raise self.TableMissingError('DocType', doctype)
pymysql.err.ProgrammingError: ('DocType', 'Custom DocPerm')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/my_user/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python3.6/inspect.py", line 1262, in formatargvalues
    specs.append(convert(args[i]))
  File "/usr/lib/python3.6/inspect.py", line 1259, in convert
    return formatarg(name) + formatvalue(locals[name])
  File "/home/my_user/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in <lambda>
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python3.6/reprlib.py", line 55, in repr
    return self.repr1(x, self.maxlevel)
  File "/usr/lib/python3.6/pydoc.py", line 1042, in repr1
    return cram(stripid(repr(x)), self.maxother)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/document.py", line 1354, in __repr__
    docstatus = f" docstatus={self.docstatus}" if self.docstatus else ""
AttributeError: 'Document' object has no attribute 'docstatus'
2021-06-08 07:33:32,539 ERROR frappe Could not take error snapshot: 'Document' object has no attribute 'docstatus'
Site: acs.v1
Form Dict: {'doctype': 'DocType', 'fields': '["`tabDocType`.`name`","`tabDocType`.`owner`","`tabDocType`.`creation`","`tabDocType`.`modified`","`tabDocType`.`modified_by`","`tabDocType`.`_user_tags`","`tabDocType`.`_comments`","`tabDocType`.`_assign`","`tabDocType`.`_liked_by`","`tabDocType`.`docstatus`","`tabDocType`.`parent`","`tabDocType`.`parenttype`","`tabDocType`.`parentfield`","`tabDocType`.`idx`","`tabDocType`.`module`","`tabDocType`.`color`"]', 'filters': '[["DocType","name","like","%Policies%"],["DocType","name","=","Property Setter"]]', 'order_by': '`tabDocType`.`modified` desc', 'start': '0', 'page_length': '20', 'view': 'List', 'with_comment_count': 'true'}
Traceback (most recent call last):
  File "/home/my_user/frappe-bench/apps/frappe/frappe/app.py", line 54, in application
    init_request(request)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/app.py", line 128, in init_request
    frappe.local.http_request = frappe.auth.HTTPRequest()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/auth.py", line 52, in __init__
    frappe.local.login_manager = LoginManager()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/auth.py", line 114, in __init__
    self.make_session(resume=True)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/auth.py", line 196, in make_session
    full_name=self.full_name, user_type=self.user_type)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/sessions.py", line 189, in __init__
    self.resume()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/sessions.py", line 256, in resume
    validate_ip_address(self.user)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/auth.py", line 380, in validate_ip_address
    user = frappe.get_cached_doc("User", user) if not frappe.flags.in_test else frappe.get_doc("User", user)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/__init__.py", line 807, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/__init__.py", line 850, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/document.py", line 74, in get_doc
    return controller(*args, **kwargs)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/document.py", line 112, in __init__
    self.load_from_db()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/document.py", line 141, in load_from_db
    if not getattr(self, "_metaclass", False) and self.meta.issingle:
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/base_document.py", line 91, in meta
    self._meta = frappe.get_meta(self.doctype)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/__init__.py", line 881, in get_meta
    return frappe.model.meta.get_meta(doctype, cached=cached)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/meta.py", line 37, in get_meta
    meta = Meta(doctype)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/meta.py", line 84, in __init__
    self.process()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/meta.py", line 105, in process
    self.set_custom_permissions()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/meta.py", line 417, in set_custom_permissions
    filters=dict(parent=self.name), update=dict(doctype='Custom DocPerm'))
  File "/home/my_user/frappe-bench/apps/frappe/frappe/__init__.py", line 1435, in get_all
    return get_list(doctype, *args, **kwargs)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/__init__.py", line 1408, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(*args, **kwargs)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/db_query.py", line 101, in execute
    self.columns = self.get_table_columns()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/db_query.py", line 338, in get_table_columns
    return get_table_columns(self.doctype)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/meta.py", line 49, in get_table_columns
    return frappe.db.get_table_columns(doctype)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/database/database.py", line 896, in get_table_columns
    raise self.TableMissingError('DocType', doctype)
pymysql.err.ProgrammingError: ('DocType', 'Custom DocPerm')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/my_user/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python3.6/inspect.py", line 1262, in formatargvalues
    specs.append(convert(args[i]))
  File "/usr/lib/python3.6/inspect.py", line 1259, in convert
    return formatarg(name) + formatvalue(locals[name])
  File "/home/my_user/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in <lambda>
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python3.6/reprlib.py", line 55, in repr
    return self.repr1(x, self.maxlevel)
  File "/usr/lib/python3.6/pydoc.py", line 1042, in repr1
    return cram(stripid(repr(x)), self.maxother)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/document.py", line 1354, in __repr__
    docstatus = f" docstatus={self.docstatus}" if self.docstatus else ""
AttributeError: 'Document' object has no attribute 'docstatus'
2021-06-08 07:33:32,598 ERROR frappe Could not take error snapshot: 'Document' object has no attribute 'docstatus'
Site: acs.v1
Form Dict: {'doctype': 'DocType', 'fields': '["`tabDocType`.`name`","`tabDocType`.`owner`","`tabDocType`.`creation`","`tabDocType`.`modified`","`tabDocType`.`modified_by`","`tabDocType`.`_user_tags`","`tabDocType`.`_comments`","`tabDocType`.`_assign`","`tabDocType`.`_liked_by`","`tabDocType`.`docstatus`","`tabDocType`.`parent`","`tabDocType`.`parenttype`","`tabDocType`.`parentfield`","`tabDocType`.`idx`","`tabDocType`.`module`","`tabDocType`.`color`"]', 'filters': '[["DocType","module","=","Participants"],["DocType","name","=","Property Setter"]]', 'order_by': '`tabDocType`.`modified` desc', 'start': '0', 'page_length': '20', 'view': 'List', 'with_comment_count': 'true'}
Traceback (most recent call last):
  File "/home/my_user/frappe-bench/apps/frappe/frappe/app.py", line 54, in application
    init_request(request)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/app.py", line 128, in init_request
    frappe.local.http_request = frappe.auth.HTTPRequest()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/auth.py", line 52, in __init__
    frappe.local.login_manager = LoginManager()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/auth.py", line 114, in __init__
    self.make_session(resume=True)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/auth.py", line 196, in make_session
    full_name=self.full_name, user_type=self.user_type)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/sessions.py", line 189, in __init__
    self.resume()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/sessions.py", line 256, in resume
    validate_ip_address(self.user)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/auth.py", line 380, in validate_ip_address
    user = frappe.get_cached_doc("User", user) if not frappe.flags.in_test else frappe.get_doc("User", user)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/__init__.py", line 807, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/__init__.py", line 850, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/document.py", line 74, in get_doc
    return controller(*args, **kwargs)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/document.py", line 112, in __init__
    self.load_from_db()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/document.py", line 141, in load_from_db
    if not getattr(self, "_metaclass", False) and self.meta.issingle:
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/base_document.py", line 91, in meta
    self._meta = frappe.get_meta(self.doctype)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/__init__.py", line 881, in get_meta
    return frappe.model.meta.get_meta(doctype, cached=cached)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/meta.py", line 37, in get_meta
    meta = Meta(doctype)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/meta.py", line 84, in __init__
    self.process()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/meta.py", line 105, in process
    self.set_custom_permissions()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/meta.py", line 417, in set_custom_permissions
    filters=dict(parent=self.name), update=dict(doctype='Custom DocPerm'))
  File "/home/my_user/frappe-bench/apps/frappe/frappe/__init__.py", line 1435, in get_all
    return get_list(doctype, *args, **kwargs)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/__init__.py", line 1408, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(*args, **kwargs)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/db_query.py", line 101, in execute
    self.columns = self.get_table_columns()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/db_query.py", line 338, in get_table_columns
    return get_table_columns(self.doctype)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/meta.py", line 49, in get_table_columns
    return frappe.db.get_table_columns(doctype)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/database/database.py", line 896, in get_table_columns
    raise self.TableMissingError('DocType', doctype)
pymysql.err.ProgrammingError: ('DocType', 'Custom DocPerm')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/my_user/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python3.6/inspect.py", line 1262, in formatargvalues
    specs.append(convert(args[i]))
  File "/usr/lib/python3.6/inspect.py", line 1259, in convert
    return formatarg(name) + formatvalue(locals[name])
  File "/home/my_user/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in <lambda>
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python3.6/reprlib.py", line 55, in repr
    return self.repr1(x, self.maxlevel)
  File "/usr/lib/python3.6/pydoc.py", line 1042, in repr1
    return cram(stripid(repr(x)), self.maxother)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/document.py", line 1354, in __repr__
    docstatus = f" docstatus={self.docstatus}" if self.docstatus else ""
AttributeError: 'Document' object has no attribute 'docstatus'
2021-06-08 07:33:32,673 ERROR frappe Could not take error snapshot: 'User' object has no attribute 'docstatus'
Site: acs.v1
Form Dict: {'doctype': 'DocType', 'fields': '["`tabDocType`.`name`","`tabDocType`.`owner`","`tabDocType`.`creation`","`tabDocType`.`modified`","`tabDocType`.`modified_by`","`tabDocType`.`_user_tags`","`tabDocType`.`_comments`","`tabDocType`.`_assign`","`tabDocType`.`_liked_by`","`tabDocType`.`docstatus`","`tabDocType`.`parent`","`tabDocType`.`parenttype`","`tabDocType`.`parentfield`","`tabDocType`.`idx`","`tabDocType`.`module`","`tabDocType`.`color`"]', 'filters': '[["DocType","module","=","Participants"],["DocType","name","=","Custom Field"]]', 'order_by': '`tabDocType`.`modified` desc', 'start': '0', 'page_length': '20', 'view': 'List', 'with_comment_count': 'true'}
Traceback (most recent call last):
  File "/home/my_user/frappe-bench/apps/frappe/frappe/app.py", line 54, in application
    init_request(request)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/app.py", line 128, in init_request
    frappe.local.http_request = frappe.auth.HTTPRequest()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/auth.py", line 52, in __init__
    frappe.local.login_manager = LoginManager()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/auth.py", line 114, in __init__
    self.make_session(resume=True)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/auth.py", line 196, in make_session
    full_name=self.full_name, user_type=self.user_type)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/sessions.py", line 189, in __init__
    self.resume()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/sessions.py", line 256, in resume
    validate_ip_address(self.user)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/auth.py", line 380, in validate_ip_address
    user = frappe.get_cached_doc("User", user) if not frappe.flags.in_test else frappe.get_doc("User", user)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/__init__.py", line 807, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/__init__.py", line 850, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/document.py", line 74, in get_doc
    return controller(*args, **kwargs)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/document.py", line 112, in __init__
    self.load_from_db()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/document.py", line 141, in load_from_db
    if not getattr(self, "_metaclass", False) and self.meta.issingle:
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/base_document.py", line 91, in meta
    self._meta = frappe.get_meta(self.doctype)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/__init__.py", line 881, in get_meta
    return frappe.model.meta.get_meta(doctype, cached=cached)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/meta.py", line 37, in get_meta
    meta = Meta(doctype)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/meta.py", line 84, in __init__
    self.process()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/meta.py", line 105, in process
    self.set_custom_permissions()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/meta.py", line 417, in set_custom_permissions
    filters=dict(parent=self.name), update=dict(doctype='Custom DocPerm'))
  File "/home/my_user/frappe-bench/apps/frappe/frappe/__init__.py", line 1435, in get_all
    return get_list(doctype, *args, **kwargs)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/__init__.py", line 1408, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(*args, **kwargs)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/db_query.py", line 101, in execute
    self.columns = self.get_table_columns()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/db_query.py", line 338, in get_table_columns
    return get_table_columns(self.doctype)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/meta.py", line 49, in get_table_columns
    return frappe.db.get_table_columns(doctype)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/database/database.py", line 896, in get_table_columns
    raise self.TableMissingError('DocType', doctype)
pymysql.err.ProgrammingError: ('DocType', 'Custom DocPerm')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/my_user/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python3.6/inspect.py", line 1262, in formatargvalues
    specs.append(convert(args[i]))
  File "/usr/lib/python3.6/inspect.py", line 1259, in convert
    return formatarg(name) + formatvalue(locals[name])
  File "/home/my_user/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in <lambda>
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python3.6/reprlib.py", line 55, in repr
    return self.repr1(x, self.maxlevel)
  File "/usr/lib/python3.6/pydoc.py", line 1042, in repr1
    return cram(stripid(repr(x)), self.maxother)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/document.py", line 1354, in __repr__
    docstatus = f" docstatus={self.docstatus}" if self.docstatus else ""
AttributeError: 'User' object has no attribute 'docstatus'
2021-06-08 07:33:32,732 ERROR frappe Could not take error snapshot: 'User' object has no attribute 'docstatus'
Site: acs.v1
Form Dict: {'doctype': 'DocType', 'fields': '["`tabDocType`.`name`","`tabDocType`.`owner`","`tabDocType`.`creation`","`tabDocType`.`modified`","`tabDocType`.`modified_by`","`tabDocType`.`_user_tags`","`tabDocType`.`_comments`","`tabDocType`.`_assign`","`tabDocType`.`_liked_by`","`tabDocType`.`docstatus`","`tabDocType`.`parent`","`tabDocType`.`parenttype`","`tabDocType`.`parentfield`","`tabDocType`.`idx`","`tabDocType`.`module`","`tabDocType`.`color`"]', 'filters': '[["DocType","module","=","Participants"],["DocType","name","=","Web Form"]]', 'order_by': '`tabDocType`.`modified` desc', 'start': '0', 'page_length': '20', 'view': 'List', 'with_comment_count': 'true'}
Traceback (most recent call last):
  File "/home/my_user/frappe-bench/apps/frappe/frappe/app.py", line 54, in application
    init_request(request)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/app.py", line 128, in init_request
    frappe.local.http_request = frappe.auth.HTTPRequest()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/auth.py", line 52, in __init__
    frappe.local.login_manager = LoginManager()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/auth.py", line 114, in __init__
    self.make_session(resume=True)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/auth.py", line 196, in make_session
    full_name=self.full_name, user_type=self.user_type)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/sessions.py", line 189, in __init__
    self.resume()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/sessions.py", line 256, in resume
    validate_ip_address(self.user)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/auth.py", line 380, in validate_ip_address
    user = frappe.get_cached_doc("User", user) if not frappe.flags.in_test else frappe.get_doc("User", user)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/__init__.py", line 807, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/__init__.py", line 850, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/document.py", line 74, in get_doc
    return controller(*args, **kwargs)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/document.py", line 112, in __init__
    self.load_from_db()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/document.py", line 141, in load_from_db
    if not getattr(self, "_metaclass", False) and self.meta.issingle:
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/base_document.py", line 91, in meta
    self._meta = frappe.get_meta(self.doctype)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/__init__.py", line 881, in get_meta
    return frappe.model.meta.get_meta(doctype, cached=cached)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/meta.py", line 37, in get_meta
    meta = Meta(doctype)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/meta.py", line 84, in __init__
    self.process()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/meta.py", line 105, in process
    self.set_custom_permissions()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/meta.py", line 417, in set_custom_permissions
    filters=dict(parent=self.name), update=dict(doctype='Custom DocPerm'))
  File "/home/my_user/frappe-bench/apps/frappe/frappe/__init__.py", line 1435, in get_all
    return get_list(doctype, *args, **kwargs)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/__init__.py", line 1408, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(*args, **kwargs)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/db_query.py", line 101, in execute
    self.columns = self.get_table_columns()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/db_query.py", line 338, in get_table_columns
    return get_table_columns(self.doctype)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/meta.py", line 49, in get_table_columns
    return frappe.db.get_table_columns(doctype)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/database/database.py", line 896, in get_table_columns
    raise self.TableMissingError('DocType', doctype)
pymysql.err.ProgrammingError: ('DocType', 'Custom DocPerm')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/my_user/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python3.6/inspect.py", line 1262, in formatargvalues
    specs.append(convert(args[i]))
  File "/usr/lib/python3.6/inspect.py", line 1259, in convert
    return formatarg(name) + formatvalue(locals[name])
  File "/home/my_user/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in <lambda>
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python3.6/reprlib.py", line 55, in repr
    return self.repr1(x, self.maxlevel)
  File "/usr/lib/python3.6/pydoc.py", line 1042, in repr1
    return cram(stripid(repr(x)), self.maxother)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/document.py", line 1354, in __repr__
    docstatus = f" docstatus={self.docstatus}" if self.docstatus else ""
AttributeError: 'User' object has no attribute 'docstatus'
2021-06-08 07:33:32,783 ERROR frappe Could not take error snapshot: 'User' object has no attribute 'docstatus'
Site: acs.v1
Form Dict: {'doctype': 'DocType', 'fields': '["`tabDocType`.`name`","`tabDocType`.`owner`","`tabDocType`.`creation`","`tabDocType`.`modified`","`tabDocType`.`modified_by`","`tabDocType`.`_user_tags`","`tabDocType`.`_comments`","`tabDocType`.`_assign`","`tabDocType`.`_liked_by`","`tabDocType`.`docstatus`","`tabDocType`.`parent`","`tabDocType`.`parenttype`","`tabDocType`.`parentfield`","`tabDocType`.`idx`","`tabDocType`.`module`","`tabDocType`.`color`"]', 'filters': '[["DocType","module","=","Participants"],["DocType","name","=","Web Template"]]', 'order_by': '`tabDocType`.`modified` desc', 'start': '0', 'page_length': '20', 'view': 'List', 'with_comment_count': 'true'}
Traceback (most recent call last):
  File "/home/my_user/frappe-bench/apps/frappe/frappe/app.py", line 54, in application
    init_request(request)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/app.py", line 128, in init_request
    frappe.local.http_request = frappe.auth.HTTPRequest()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/auth.py", line 52, in __init__
    frappe.local.login_manager = LoginManager()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/auth.py", line 114, in __init__
    self.make_session(resume=True)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/auth.py", line 196, in make_session
    full_name=self.full_name, user_type=self.user_type)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/sessions.py", line 189, in __init__
    self.resume()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/sessions.py", line 256, in resume
    validate_ip_address(self.user)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/auth.py", line 380, in validate_ip_address
    user = frappe.get_cached_doc("User", user) if not frappe.flags.in_test else frappe.get_doc("User", user)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/__init__.py", line 807, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/__init__.py", line 850, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/document.py", line 74, in get_doc
    return controller(*args, **kwargs)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/document.py", line 112, in __init__
    self.load_from_db()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/document.py", line 141, in load_from_db
    if not getattr(self, "_metaclass", False) and self.meta.issingle:
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/base_document.py", line 91, in meta
    self._meta = frappe.get_meta(self.doctype)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/__init__.py", line 881, in get_meta
    return frappe.model.meta.get_meta(doctype, cached=cached)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/meta.py", line 37, in get_meta
    meta = Meta(doctype)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/meta.py", line 84, in __init__
    self.process()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/meta.py", line 105, in process
    self.set_custom_permissions()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/meta.py", line 417, in set_custom_permissions
    filters=dict(parent=self.name), update=dict(doctype='Custom DocPerm'))
  File "/home/my_user/frappe-bench/apps/frappe/frappe/__init__.py", line 1435, in get_all
    return get_list(doctype, *args, **kwargs)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/__init__.py", line 1408, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(*args, **kwargs)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/db_query.py", line 101, in execute
    self.columns = self.get_table_columns()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/db_query.py", line 338, in get_table_columns
    return get_table_columns(self.doctype)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/meta.py", line 49, in get_table_columns
    return frappe.db.get_table_columns(doctype)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/database/database.py", line 896, in get_table_columns
    raise self.TableMissingError('DocType', doctype)
pymysql.err.ProgrammingError: ('DocType', 'Custom DocPerm')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/my_user/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python3.6/inspect.py", line 1262, in formatargvalues
    specs.append(convert(args[i]))
  File "/usr/lib/python3.6/inspect.py", line 1259, in convert
    return formatarg(name) + formatvalue(locals[name])
  File "/home/my_user/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in <lambda>
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python3.6/reprlib.py", line 55, in repr
    return self.repr1(x, self.maxlevel)
  File "/usr/lib/python3.6/pydoc.py", line 1042, in repr1
    return cram(stripid(repr(x)), self.maxother)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/document.py", line 1354, in __repr__
    docstatus = f" docstatus={self.docstatus}" if self.docstatus else ""
AttributeError: 'User' object has no attribute 'docstatus'
2021-06-08 07:33:32,835 ERROR frappe Could not take error snapshot: 'Document' object has no attribute 'docstatus'
Site: acs.v1
Form Dict: {'doctype': 'DocType', 'fields': '["`tabDocType`.`name`","`tabDocType`.`owner`","`tabDocType`.`creation`","`tabDocType`.`modified`","`tabDocType`.`modified_by`","`tabDocType`.`_user_tags`","`tabDocType`.`_comments`","`tabDocType`.`_assign`","`tabDocType`.`_liked_by`","`tabDocType`.`docstatus`","`tabDocType`.`parent`","`tabDocType`.`parenttype`","`tabDocType`.`parentfield`","`tabDocType`.`idx`","`tabDocType`.`module`","`tabDocType`.`color`"]', 'filters': '[["DocType","name","like","%Policies%"],["DocType","name","=","Web Form"]]', 'order_by': '`tabDocType`.`modified` desc', 'start': '0', 'page_length': '20', 'view': 'List', 'with_comment_count': 'true'}
Traceback (most recent call last):
  File "/home/my_user/frappe-bench/apps/frappe/frappe/app.py", line 54, in application
    init_request(request)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/app.py", line 128, in init_request
    frappe.local.http_request = frappe.auth.HTTPRequest()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/auth.py", line 52, in __init__
    frappe.local.login_manager = LoginManager()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/auth.py", line 114, in __init__
    self.make_session(resume=True)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/auth.py", line 196, in make_session
    full_name=self.full_name, user_type=self.user_type)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/sessions.py", line 189, in __init__
    self.resume()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/sessions.py", line 256, in resume
    validate_ip_address(self.user)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/auth.py", line 380, in validate_ip_address
    user = frappe.get_cached_doc("User", user) if not frappe.flags.in_test else frappe.get_doc("User", user)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/__init__.py", line 807, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/__init__.py", line 850, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/document.py", line 74, in get_doc
    return controller(*args, **kwargs)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/document.py", line 112, in __init__
    self.load_from_db()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/document.py", line 141, in load_from_db
    if not getattr(self, "_metaclass", False) and self.meta.issingle:
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/base_document.py", line 91, in meta
    self._meta = frappe.get_meta(self.doctype)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/__init__.py", line 881, in get_meta
    return frappe.model.meta.get_meta(doctype, cached=cached)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/meta.py", line 37, in get_meta
    meta = Meta(doctype)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/meta.py", line 84, in __init__
    self.process()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/meta.py", line 105, in process
    self.set_custom_permissions()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/meta.py", line 417, in set_custom_permissions
    filters=dict(parent=self.name), update=dict(doctype='Custom DocPerm'))
  File "/home/my_user/frappe-bench/apps/frappe/frappe/__init__.py", line 1435, in get_all
    return get_list(doctype, *args, **kwargs)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/__init__.py", line 1408, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(*args, **kwargs)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/db_query.py", line 101, in execute
    self.columns = self.get_table_columns()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/db_query.py", line 338, in get_table_columns
    return get_table_columns(self.doctype)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/meta.py", line 49, in get_table_columns
    return frappe.db.get_table_columns(doctype)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/database/database.py", line 896, in get_table_columns
    raise self.TableMissingError('DocType', doctype)
pymysql.err.ProgrammingError: ('DocType', 'Custom DocPerm')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/my_user/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python3.6/inspect.py", line 1262, in formatargvalues
    specs.append(convert(args[i]))
  File "/usr/lib/python3.6/inspect.py", line 1259, in convert
    return formatarg(name) + formatvalue(locals[name])
  File "/home/my_user/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in <lambda>
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python3.6/reprlib.py", line 55, in repr
    return self.repr1(x, self.maxlevel)
  File "/usr/lib/python3.6/pydoc.py", line 1042, in repr1
    return cram(stripid(repr(x)), self.maxother)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/document.py", line 1354, in __repr__
    docstatus = f" docstatus={self.docstatus}" if self.docstatus else ""
AttributeError: 'Document' object has no attribute 'docstatus'
2021-06-08 07:33:32,909 ERROR frappe Could not take error snapshot: 'Document' object has no attribute 'docstatus'
Site: acs.v1
Form Dict: {'doctype': 'DocType', 'fields': '["`tabDocType`.`name`","`tabDocType`.`owner`","`tabDocType`.`creation`","`tabDocType`.`modified`","`tabDocType`.`modified_by`","`tabDocType`.`_user_tags`","`tabDocType`.`_comments`","`tabDocType`.`_assign`","`tabDocType`.`_liked_by`","`tabDocType`.`docstatus`","`tabDocType`.`parent`","`tabDocType`.`parenttype`","`tabDocType`.`parentfield`","`tabDocType`.`idx`","`tabDocType`.`module`","`tabDocType`.`color`"]', 'filters': '[["DocType","module","=","Participants"],["DocType","name","=","Web Form Field"]]', 'order_by': '`tabDocType`.`modified` desc', 'start': '0', 'page_length': '20', 'view': 'List', 'with_comment_count': 'true'}
Traceback (most recent call last):
  File "/home/my_user/frappe-bench/apps/frappe/frappe/app.py", line 54, in application
    init_request(request)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/app.py", line 128, in init_request
    frappe.local.http_request = frappe.auth.HTTPRequest()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/auth.py", line 52, in __init__
    frappe.local.login_manager = LoginManager()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/auth.py", line 114, in __init__
    self.make_session(resume=True)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/auth.py", line 196, in make_session
    full_name=self.full_name, user_type=self.user_type)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/sessions.py", line 189, in __init__
    self.resume()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/sessions.py", line 256, in resume
    validate_ip_address(self.user)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/auth.py", line 380, in validate_ip_address
    user = frappe.get_cached_doc("User", user) if not frappe.flags.in_test else frappe.get_doc("User", user)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/__init__.py", line 807, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/__init__.py", line 850, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/document.py", line 74, in get_doc
    return controller(*args, **kwargs)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/document.py", line 112, in __init__
    self.load_from_db()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/document.py", line 141, in load_from_db
    if not getattr(self, "_metaclass", False) and self.meta.issingle:
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/base_document.py", line 91, in meta
    self._meta = frappe.get_meta(self.doctype)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/__init__.py", line 881, in get_meta
    return frappe.model.meta.get_meta(doctype, cached=cached)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/meta.py", line 37, in get_meta
    meta = Meta(doctype)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/meta.py", line 84, in __init__
    self.process()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/meta.py", line 105, in process
    self.set_custom_permissions()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/meta.py", line 417, in set_custom_permissions
    filters=dict(parent=self.name), update=dict(doctype='Custom DocPerm'))
  File "/home/my_user/frappe-bench/apps/frappe/frappe/__init__.py", line 1435, in get_all
    return get_list(doctype, *args, **kwargs)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/__init__.py", line 1408, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(*args, **kwargs)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/db_query.py", line 101, in execute
    self.columns = self.get_table_columns()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/db_query.py", line 338, in get_table_columns
    return get_table_columns(self.doctype)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/meta.py", line 49, in get_table_columns
    return frappe.db.get_table_columns(doctype)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/database/database.py", line 896, in get_table_columns
    raise self.TableMissingError('DocType', doctype)
pymysql.err.ProgrammingError: ('DocType', 'Custom DocPerm')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/my_user/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python3.6/inspect.py", line 1262, in formatargvalues
    specs.append(convert(args[i]))
  File "/usr/lib/python3.6/inspect.py", line 1259, in convert
    return formatarg(name) + formatvalue(locals[name])
  File "/home/my_user/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in <lambda>
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python3.6/reprlib.py", line 55, in repr
    return self.repr1(x, self.maxlevel)
  File "/usr/lib/python3.6/pydoc.py", line 1042, in repr1
    return cram(stripid(repr(x)), self.maxother)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/document.py", line 1354, in __repr__
    docstatus = f" docstatus={self.docstatus}" if self.docstatus else ""
AttributeError: 'Document' object has no attribute 'docstatus'
2021-06-08 07:33:32,976 ERROR frappe Could not take error snapshot: 'User' object has no attribute 'docstatus'
Site: acs.v1
Form Dict: {'doctype': 'DocType', 'fields': '["`tabDocType`.`name`","`tabDocType`.`owner`","`tabDocType`.`creation`","`tabDocType`.`modified`","`tabDocType`.`modified_by`","`tabDocType`.`_user_tags`","`tabDocType`.`_comments`","`tabDocType`.`_assign`","`tabDocType`.`_liked_by`","`tabDocType`.`docstatus`","`tabDocType`.`parent`","`tabDocType`.`parenttype`","`tabDocType`.`parentfield`","`tabDocType`.`idx`","`tabDocType`.`module`","`tabDocType`.`color`"]', 'filters': '[["DocType","name","like","%Policies%"],["DocType","name","=","Web Form Field"]]', 'order_by': '`tabDocType`.`modified` desc', 'start': '0', 'page_length': '20', 'view': 'List', 'with_comment_count': 'true'}
Traceback (most recent call last):
  File "/home/my_user/frappe-bench/apps/frappe/frappe/app.py", line 54, in application
    init_request(request)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/app.py", line 128, in init_request
    frappe.local.http_request = frappe.auth.HTTPRequest()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/auth.py", line 52, in __init__
    frappe.local.login_manager = LoginManager()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/auth.py", line 114, in __init__
    self.make_session(resume=True)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/auth.py", line 196, in make_session
    full_name=self.full_name, user_type=self.user_type)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/sessions.py", line 189, in __init__
    self.resume()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/sessions.py", line 256, in resume
    validate_ip_address(self.user)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/auth.py", line 380, in validate_ip_address
    user = frappe.get_cached_doc("User", user) if not frappe.flags.in_test else frappe.get_doc("User", user)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/__init__.py", line 807, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/__init__.py", line 850, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/document.py", line 74, in get_doc
    return controller(*args, **kwargs)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/document.py", line 112, in __init__
    self.load_from_db()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/document.py", line 141, in load_from_db
    if not getattr(self, "_metaclass", False) and self.meta.issingle:
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/base_document.py", line 91, in meta
    self._meta = frappe.get_meta(self.doctype)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/__init__.py", line 881, in get_meta
    return frappe.model.meta.get_meta(doctype, cached=cached)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/meta.py", line 37, in get_meta
    meta = Meta(doctype)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/meta.py", line 84, in __init__
    self.process()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/meta.py", line 105, in process
    self.set_custom_permissions()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/meta.py", line 417, in set_custom_permissions
    filters=dict(parent=self.name), update=dict(doctype='Custom DocPerm'))
  File "/home/my_user/frappe-bench/apps/frappe/frappe/__init__.py", line 1435, in get_all
    return get_list(doctype, *args, **kwargs)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/__init__.py", line 1408, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(*args, **kwargs)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/db_query.py", line 101, in execute
    self.columns = self.get_table_columns()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/db_query.py", line 338, in get_table_columns
    return get_table_columns(self.doctype)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/meta.py", line 49, in get_table_columns
    return frappe.db.get_table_columns(doctype)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/database/database.py", line 896, in get_table_columns
    raise self.TableMissingError('DocType', doctype)
pymysql.err.ProgrammingError: ('DocType', 'Custom DocPerm')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/my_user/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python3.6/inspect.py", line 1262, in formatargvalues
    specs.append(convert(args[i]))
  File "/usr/lib/python3.6/inspect.py", line 1259, in convert
    return formatarg(name) + formatvalue(locals[name])
  File "/home/my_user/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in <lambda>
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python3.6/reprlib.py", line 55, in repr
    return self.repr1(x, self.maxlevel)
  File "/usr/lib/python3.6/pydoc.py", line 1042, in repr1
    return cram(stripid(repr(x)), self.maxother)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/document.py", line 1354, in __repr__
    docstatus = f" docstatus={self.docstatus}" if self.docstatus else ""
AttributeError: 'User' object has no attribute 'docstatus'
2021-06-08 07:33:33,036 ERROR frappe Could not take error snapshot: 'Document' object has no attribute 'docstatus'
Site: acs.v1
Form Dict: {'doctype': 'DocType', 'fields': '["`tabDocType`.`name`","`tabDocType`.`owner`","`tabDocType`.`creation`","`tabDocType`.`modified`","`tabDocType`.`modified_by`","`tabDocType`.`_user_tags`","`tabDocType`.`_comments`","`tabDocType`.`_assign`","`tabDocType`.`_liked_by`","`tabDocType`.`docstatus`","`tabDocType`.`parent`","`tabDocType`.`parenttype`","`tabDocType`.`parentfield`","`tabDocType`.`idx`","`tabDocType`.`module`","`tabDocType`.`color`"]', 'filters': '[["DocType","name","like","%Policies%"],["DocType","name","=","Portal Menu Item"]]', 'order_by': '`tabDocType`.`modified` desc', 'start': '0', 'page_length': '20', 'view': 'List', 'with_comment_count': 'true'}
Traceback (most recent call last):
  File "/home/my_user/frappe-bench/apps/frappe/frappe/app.py", line 54, in application
    init_request(request)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/app.py", line 128, in init_request
    frappe.local.http_request = frappe.auth.HTTPRequest()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/auth.py", line 52, in __init__
    frappe.local.login_manager = LoginManager()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/auth.py", line 114, in __init__
    self.make_session(resume=True)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/auth.py", line 196, in make_session
    full_name=self.full_name, user_type=self.user_type)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/sessions.py", line 189, in __init__
    self.resume()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/sessions.py", line 256, in resume
    validate_ip_address(self.user)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/auth.py", line 380, in validate_ip_address
    user = frappe.get_cached_doc("User", user) if not frappe.flags.in_test else frappe.get_doc("User", user)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/__init__.py", line 807, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/__init__.py", line 850, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/document.py", line 74, in get_doc
    return controller(*args, **kwargs)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/document.py", line 112, in __init__
    self.load_from_db()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/document.py", line 141, in load_from_db
    if not getattr(self, "_metaclass", False) and self.meta.issingle:
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/base_document.py", line 91, in meta
    self._meta = frappe.get_meta(self.doctype)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/__init__.py", line 881, in get_meta
    return frappe.model.meta.get_meta(doctype, cached=cached)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/meta.py", line 37, in get_meta
    meta = Meta(doctype)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/meta.py", line 84, in __init__
    self.process()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/meta.py", line 105, in process
    self.set_custom_permissions()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/meta.py", line 417, in set_custom_permissions
    filters=dict(parent=self.name), update=dict(doctype='Custom DocPerm'))
  File "/home/my_user/frappe-bench/apps/frappe/frappe/__init__.py", line 1435, in get_all
    return get_list(doctype, *args, **kwargs)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/__init__.py", line 1408, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(*args, **kwargs)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/db_query.py", line 101, in execute
    self.columns = self.get_table_columns()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/db_query.py", line 338, in get_table_columns
    return get_table_columns(self.doctype)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/meta.py", line 49, in get_table_columns
    return frappe.db.get_table_columns(doctype)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/database/database.py", line 896, in get_table_columns
    raise self.TableMissingError('DocType', doctype)
pymysql.err.ProgrammingError: ('DocType', 'Custom DocPerm')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/my_user/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python3.6/inspect.py", line 1262, in formatargvalues
    specs.append(convert(args[i]))
  File "/usr/lib/python3.6/inspect.py", line 1259, in convert
    return formatarg(name) + formatvalue(locals[name])
  File "/home/my_user/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in <lambda>
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python3.6/reprlib.py", line 55, in repr
    return self.repr1(x, self.maxlevel)
  File "/usr/lib/python3.6/pydoc.py", line 1042, in repr1
    return cram(stripid(repr(x)), self.maxother)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/document.py", line 1354, in __repr__
    docstatus = f" docstatus={self.docstatus}" if self.docstatus else ""
AttributeError: 'Document' object has no attribute 'docstatus'
2021-06-08 07:33:33,043 ERROR frappe Could not take error snapshot: 'User' object has no attribute 'docstatus'
Site: acs.v1
Form Dict: {'doctype': 'DocType', 'fields': '["`tabDocType`.`name`","`tabDocType`.`owner`","`tabDocType`.`creation`","`tabDocType`.`modified`","`tabDocType`.`modified_by`","`tabDocType`.`_user_tags`","`tabDocType`.`_comments`","`tabDocType`.`_assign`","`tabDocType`.`_liked_by`","`tabDocType`.`docstatus`","`tabDocType`.`parent`","`tabDocType`.`parenttype`","`tabDocType`.`parentfield`","`tabDocType`.`idx`","`tabDocType`.`module`","`tabDocType`.`color`"]', 'filters': '[["DocType","name","like","%Policies%"],["DocType","name","=","Web Template"]]', 'order_by': '`tabDocType`.`modified` desc', 'start': '0', 'page_length': '20', 'view': 'List', 'with_comment_count': 'true'}
Traceback (most recent call last):
  File "/home/my_user/frappe-bench/apps/frappe/frappe/app.py", line 54, in application
    init_request(request)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/app.py", line 128, in init_request
    frappe.local.http_request = frappe.auth.HTTPRequest()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/auth.py", line 52, in __init__
    frappe.local.login_manager = LoginManager()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/auth.py", line 114, in __init__
    self.make_session(resume=True)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/auth.py", line 196, in make_session
    full_name=self.full_name, user_type=self.user_type)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/sessions.py", line 189, in __init__
    self.resume()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/sessions.py", line 256, in resume
    validate_ip_address(self.user)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/auth.py", line 380, in validate_ip_address
    user = frappe.get_cached_doc("User", user) if not frappe.flags.in_test else frappe.get_doc("User", user)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/__init__.py", line 807, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/__init__.py", line 850, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/document.py", line 74, in get_doc
    return controller(*args, **kwargs)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/document.py", line 112, in __init__
    self.load_from_db()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/document.py", line 141, in load_from_db
    if not getattr(self, "_metaclass", False) and self.meta.issingle:
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/base_document.py", line 91, in meta
    self._meta = frappe.get_meta(self.doctype)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/__init__.py", line 881, in get_meta
    return frappe.model.meta.get_meta(doctype, cached=cached)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/meta.py", line 37, in get_meta
    meta = Meta(doctype)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/meta.py", line 84, in __init__
    self.process()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/meta.py", line 105, in process
    self.set_custom_permissions()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/meta.py", line 417, in set_custom_permissions
    filters=dict(parent=self.name), update=dict(doctype='Custom DocPerm'))
  File "/home/my_user/frappe-bench/apps/frappe/frappe/__init__.py", line 1435, in get_all
    return get_list(doctype, *args, **kwargs)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/__init__.py", line 1408, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(*args, **kwargs)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/db_query.py", line 101, in execute
    self.columns = self.get_table_columns()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/db_query.py", line 338, in get_table_columns
    return get_table_columns(self.doctype)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/meta.py", line 49, in get_table_columns
    return frappe.db.get_table_columns(doctype)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/database/database.py", line 896, in get_table_columns
    raise self.TableMissingError('DocType', doctype)
pymysql.err.ProgrammingError: ('DocType', 'Custom DocPerm')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/my_user/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python3.6/inspect.py", line 1262, in formatargvalues
    specs.append(convert(args[i]))
  File "/usr/lib/python3.6/inspect.py", line 1259, in convert
    return formatarg(name) + formatvalue(locals[name])
  File "/home/my_user/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in <lambda>
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python3.6/reprlib.py", line 55, in repr
    return self.repr1(x, self.maxlevel)
  File "/usr/lib/python3.6/pydoc.py", line 1042, in repr1
    return cram(stripid(repr(x)), self.maxother)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/document.py", line 1354, in __repr__
    docstatus = f" docstatus={self.docstatus}" if self.docstatus else ""
AttributeError: 'User' object has no attribute 'docstatus'
2021-06-08 07:33:33,118 ERROR frappe Could not take error snapshot: 'User' object has no attribute 'docstatus'
Site: acs.v1
Form Dict: {'doctype': 'DocType', 'fields': '["`tabDocType`.`name`","`tabDocType`.`owner`","`tabDocType`.`creation`","`tabDocType`.`modified`","`tabDocType`.`modified_by`","`tabDocType`.`_user_tags`","`tabDocType`.`_comments`","`tabDocType`.`_assign`","`tabDocType`.`_liked_by`","`tabDocType`.`docstatus`","`tabDocType`.`parent`","`tabDocType`.`parenttype`","`tabDocType`.`parentfield`","`tabDocType`.`idx`","`tabDocType`.`module`","`tabDocType`.`color`"]', 'filters': '[["DocType","name","like","%Policies%"],["DocType","name","=","Data Migration Mapping Detail"]]', 'order_by': '`tabDocType`.`modified` desc', 'start': '0', 'page_length': '20', 'view': 'List', 'with_comment_count': 'true'}
Traceback (most recent call last):
  File "/home/my_user/frappe-bench/apps/frappe/frappe/app.py", line 54, in application
    init_request(request)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/app.py", line 128, in init_request
    frappe.local.http_request = frappe.auth.HTTPRequest()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/auth.py", line 52, in __init__
    frappe.local.login_manager = LoginManager()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/auth.py", line 114, in __init__
    self.make_session(resume=True)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/auth.py", line 196, in make_session
    full_name=self.full_name, user_type=self.user_type)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/sessions.py", line 189, in __init__
    self.resume()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/sessions.py", line 256, in resume
    validate_ip_address(self.user)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/auth.py", line 380, in validate_ip_address
    user = frappe.get_cached_doc("User", user) if not frappe.flags.in_test else frappe.get_doc("User", user)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/__init__.py", line 807, in get_cached_doc
    doc = get_doc(*args, **kwargs)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/__init__.py", line 850, in get_doc
    doc = frappe.model.document.get_doc(*args, **kwargs)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/document.py", line 74, in get_doc
    return controller(*args, **kwargs)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/document.py", line 112, in __init__
    self.load_from_db()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/document.py", line 141, in load_from_db
    if not getattr(self, "_metaclass", False) and self.meta.issingle:
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/base_document.py", line 91, in meta
    self._meta = frappe.get_meta(self.doctype)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/__init__.py", line 881, in get_meta
    return frappe.model.meta.get_meta(doctype, cached=cached)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/meta.py", line 37, in get_meta
    meta = Meta(doctype)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/meta.py", line 84, in __init__
    self.process()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/meta.py", line 105, in process
    self.set_custom_permissions()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/meta.py", line 417, in set_custom_permissions
    filters=dict(parent=self.name), update=dict(doctype='Custom DocPerm'))
  File "/home/my_user/frappe-bench/apps/frappe/frappe/__init__.py", line 1435, in get_all
    return get_list(doctype, *args, **kwargs)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/__init__.py", line 1408, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(*args, **kwargs)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/db_query.py", line 101, in execute
    self.columns = self.get_table_columns()
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/db_query.py", line 338, in get_table_columns
    return get_table_columns(self.doctype)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/meta.py", line 49, in get_table_columns
    return frappe.db.get_table_columns(doctype)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/database/database.py", line 896, in get_table_columns
    raise self.TableMissingError('DocType', doctype)
pymysql.err.ProgrammingError: ('DocType', 'Custom DocPerm')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/my_user/frappe-bench/apps/frappe/frappe/utils/error.py", line 36, in make_error_snapshot
    snapshot = get_snapshot(exception)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in get_snapshot
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python3.6/inspect.py", line 1262, in formatargvalues
    specs.append(convert(args[i]))
  File "/usr/lib/python3.6/inspect.py", line 1259, in convert
    return formatarg(name) + formatvalue(locals[name])
  File "/home/my_user/frappe-bench/apps/frappe/frappe/utils/error.py", line 81, in <lambda>
    call = inspect.formatargvalues(args, varargs, varkw, locals, formatvalue=lambda value: '={}'.format(pydoc.text.repr(value)))
  File "/usr/lib/python3.6/reprlib.py", line 55, in repr
    return self.repr1(x, self.maxlevel)
  File "/usr/lib/python3.6/pydoc.py", line 1042, in repr1
    return cram(stripid(repr(x)), self.maxother)
  File "/home/my_user/frappe-bench/apps/frappe/frappe/model/document.py", line 1354, in __repr__
    docstatus = f" docstatus={self.docstatus}" if self.docstatus else ""
AttributeError: 'User' object has no attribute 'docstatus'
2021-06-08 08:00:44,434 ERROR frappe New Exception collected with id: 2021-06-08 08:00:44.426639-103.11.207.116-1aa
Site: acs.v1
Form Dict: {'sid': 'Guest', 'cmd': 'frappe.realtime.get_user_info'}
2021-06-08 08:03:45,343 ERROR frappe New Exception collected with id: 2021-06-08 08:03:45.337046-103.11.207.116-bf9
Site: acs.v1
Form Dict: {'sid': 'Guest', 'cmd': 'frappe.realtime.get_user_info'}
2021-06-08 08:10:30,743 ERROR frappe New Exception collected with id: 2021-06-08 08:10:30.739532-103.11.207.116-c04
Site: acs.v1
Form Dict: {'sid': 'Guest', 'cmd': 'frappe.realtime.get_user_info'}
2021-06-08 08:18:56,522 ERROR frappe New Exception collected with id: 2021-06-08 08:18:56.515584-103.11.207.116-195
Site: acs.v1
Form Dict: {'sid': 'Guest', 'cmd': 'frappe.realtime.get_user_info'}
